// Package noderunner embeds CometBFT consensus into the fairspeed-dex binary.
//
// Instead of running CometBFT as a separate process and connecting via ABCI
// socket, RunNode starts consensus in-process using proxy.NewLocalClientCreator.
// This produces a single deployable binary with no external dependencies.
package noderunner

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	cmtconfig "github.com/cometbft/cometbft/config"
	cmted25519 "github.com/cometbft/cometbft/crypto/ed25519"
	cmtlog "github.com/cometbft/cometbft/libs/log"
	cmtservice "github.com/cometbft/cometbft/libs/service"
	cmtnode "github.com/cometbft/cometbft/node"
	cmtp2p "github.com/cometbft/cometbft/p2p"
	cmtprivval "github.com/cometbft/cometbft/privval"
	cmtproxy "github.com/cometbft/cometbft/proxy"

	localabci "github.com/byunghee1994/fairspeed-dex/internal/abci"
	"github.com/byunghee1994/fairspeed-dex/internal/abciserver"
	"github.com/byunghee1994/fairspeed-dex/internal/asset"
	"github.com/byunghee1994/fairspeed-dex/internal/genesis"
	"github.com/byunghee1994/fairspeed-dex/internal/node"
)

// configFilePath returns the path to config.toml inside homeDir.
func configFilePath(homeDir string) string {
	return filepath.Join(homeDir, cmtconfig.DefaultConfigDir, cmtconfig.DefaultConfigFileName)
}

// InitNode initialises the home directory for a new node.
// It generates node and validator keys, and writes a single-validator genesis.json.
// For multi-validator chains, replace genesis.json after collecting all keys.
func InitNode(homeDir, chainId, moniker string) error {
	cfg := cmtconfig.DefaultConfig()
	cfg.SetRoot(homeDir)
	cfg.Moniker = moniker

	// Create required directories.
	for _, dir := range []string{cfg.DBDir(), filepath.Dir(cfg.GenesisFile())} {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("mkdir %s: %w", dir, err)
		}
	}

	// Generate node key (P2P identity).
	nodeKey, err := cmtp2p.LoadOrGenNodeKey(cfg.NodeKeyFile())
	if err != nil {
		return fmt.Errorf("gen node key: %w", err)
	}
	fmt.Printf("Node ID    : %s\n", nodeKey.ID())

	// Generate validator key.
	privKey := cmted25519.GenPrivKey()
	pv2 := cmtprivval.NewFilePV(privKey, cfg.PrivValidatorKeyFile(), cfg.PrivValidatorStateFile())
	pv2.Save()
	pubKey, err := pv2.GetPubKey()
	if err != nil {
		return fmt.Errorf("get pub key: %w", err)
	}
	fmt.Printf("Validator  : %s\n", pubKey.Address())

	// Write default genesis (single-validator, BTC+USDC registered).
	doc, err := genesis.BuildGenesisDoc(chainId, []genesis.ValidatorEntry{
		{PubKey: pubKey, Power: 100, Name: moniker},
	}, genesis.DefaultAppState())
	if err != nil {
		return fmt.Errorf("build genesis: %w", err)
	}
	if err := genesis.WriteGenesisDoc(doc, cfg); err != nil {
		return fmt.Errorf("write genesis: %w", err)
	}

	// Write config.toml.
	cmtconfig.WriteConfigFile(configFilePath(homeDir), cfg)
	fmt.Printf("Home dir   : %s\n", homeDir)
	fmt.Printf("Chain ID   : %s\n", chainId)
	return nil
}

// RunNode starts an embedded CometBFT node with the DEX application.
// It blocks until the returned service is stopped.
func RunNode(ctx context.Context, homeDir string, logEvents bool) (cmtservice.Service, error) {
	cmtCfg := cmtconfig.DefaultConfig()
	cmtCfg.SetRoot(homeDir)

	// Build the DEX application.
	dexNode := node.NewLocalNode()
	dexNode.RegisterAsset(asset.BTC)
	dexNode.RegisterAsset(asset.USDC)

	dexApp := localabci.NewDEXApplication(dexNode)
	adapter := abciserver.NewCometBFTAdapter(dexApp)

	var logger cmtlog.Logger
	if logEvents {
		logger = cmtlog.NewTMLogger(cmtlog.NewSyncWriter(os.Stdout)).With("module", "fairspeed")
	} else {
		logger = cmtlog.NewNopLogger()
	}

	// Load keys (generated by InitNode).
	nodeKey, err := cmtp2p.LoadOrGenNodeKey(cmtCfg.NodeKeyFile())
	if err != nil {
		return nil, fmt.Errorf("load node key: %w", err)
	}

	privKey := cmted25519.GenPrivKey()
	pv := cmtprivval.NewFilePV(privKey, cmtCfg.PrivValidatorKeyFile(), cmtCfg.PrivValidatorStateFile())
	// Use existing key if present.
	if _, err := os.Stat(cmtCfg.PrivValidatorKeyFile()); err == nil {
		pv = cmtprivval.LoadFilePV(cmtCfg.PrivValidatorKeyFile(), cmtCfg.PrivValidatorStateFile())
	} else {
		pv.Save()
	}

	// Create and start embedded CometBFT node.
	cmtNode, err := cmtnode.NewNode(
		ctx,
		cmtCfg,
		pv,
		nodeKey,
		cmtproxy.NewLocalClientCreator(adapter),
		cmtnode.DefaultGenesisDocProviderFunc(cmtCfg),
		cmtconfig.DefaultDBProvider,
		cmtnode.DefaultMetricsProvider(cmtCfg.Instrumentation),
		logger,
	)
	if err != nil {
		return nil, fmt.Errorf("create cometbft node: %w", err)
	}
	if err := cmtNode.Start(); err != nil {
		return nil, fmt.Errorf("start cometbft node: %w", err)
	}
	return cmtNode, nil
}
